import type { Metadata } from "next";
import { Old_Standard_TT } from "next/font/google"; // Import Old Standard TT
import "./globals.css";

// Specify the desired weights
const oldStandardTT = Old_Standard_TT({ 
  subsets: ["latin"], 
  weight: ["400", "700"], // Include the weights you want to use
  variable: "--font-oldstandard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> {/* Apply font directly */}
      <body className={oldStandardTT.variable}>{children}</body>
    </html>
  );
}
